Renamed account to customer.
payfunc/service-ch3d2 pull request #68
Opened 2021-06-22 07:13 UTC by marcushanses

2021-06-22 07:53 UTC, robinnedergard requested changes
Can't use, can a clean install fix it?

2021-06-22 14:27 UTC, florianebmeier approved these changes

2021-06-23 06:49 UTC, nilssonemma approved these changes

2021-06-23 19:23 UTC, robinnedergard approved these changes

2021-06-23 21:08 UTC, fredrikbryntesson approved these changes

2021-06-23 21:08 UTC, merged